CREATE TABLE EMPLOYEE(
MaNV INT NOT NULL PRIMARY KEY,
Email VARCHAR2(50),
Ten VARCHAR2(50)
);
CREATE TABLE ACCOUNT(
Username VARCHAR2(50) NOT NULL PRIMARY KEY,
System VARCHAR2(50),
MaNV INT NOT NULL,
CONSTRAINT fk_account_employee FOREIGN KEY (MaNV)
    REFERENCES EMPLOYEE(MaNV)
    ON DELETE CASCADE
);
INSERT INTO EMPLOYEE (MaNV,Email,Ten) 
VALUES (1, 'a@example.com', 'Nguyen Van A');
INSERT INTO EMPLOYEE (MaNV,Email,Ten) 
VALUES (2, 'b@example.com', 'Nguyen Van B');

INSERT INTO ACCOUNT (Username, System, MaNV)
VALUES ('Abc', 'Quay', 1);
INSERT INTO ACCOUNT (Username, System, MaNV)
VALUES ('Aaa', 'QLthe', 1);
INSERT INTO ACCOUNT (Username, System, MaNV)
VALUES ('Bbb', 'Quay', 2);
SELECT * FROM EMPLOYEE;
SELECT * FROM ACCOUNT;